SELECT NAME,SID FROM SYS.DATABASE_PRINCIPALS

WHERE

TYPE = 'U' --Users only

AND AUTHENTICATION_TYPE = 3 --Windows Logins only

AND NAME NOT LIKE 'DBO'

EXCEPT

(SELECT DP.NAME, DP.SID FROM SYS.DATABASE_PRINCIPALS DP

INNER JOIN SYS.SERVER_PRINCIPALS SP ON DP.SID = SP.SID 

WHERE DP.TYPE = 'U'

AND DP.AUTHENTICATION_TYPE = 3)