@echo off
:: This script is generated by the Microsoft(c) SQL Server(c) Kerberos Configuration Manager tool.
:: The script may update the system information, SPN settings and Delegation configurations of a given server.
:: SPN and Delegation configuration updates require Windows Domain Administrator permission to execute.
:: A Domain Admin should review the configurations recommended by this tool and take appropriate actions to enable Kerberos authentication.
:: Please contact Microsoft Support if Kerberos connection problem persists.

:: The file is intended to be run in domain "FHLBDM.com"

echo Changing SPN configuration may affect other services running on the same machine. By selecting to continue, the following action(s) will be performed:
echo.
echo 	Remove SPN "MSSQLSvc/PVSTSAPP01.FHLBDM.com:1433" from account "FHLBDM\PVSTSAPP01$"

echo 	Add SPN "MSSQLSvc/PVSTSAPP01.FHLBDM.com:1433" to account "FHLBDM\FHLBDMSQLSrvc"


echo.
echo It may take several minutes for the updated SPN information to be visible to all servers in the domain. For more information, go to http://go.microsoft.com/fwlink/?LinkID=316972 .
echo.

:Prompt
set /p answer=Are you sure you want to continue? (Y/N):

if %answer% == Y goto Yes
if %answer% == y goto Yes
if %answer% == N goto No
if %answer% == n goto No

cls
echo Unknown input
goto Prompt

:No
exit

:Yes

SetSPN -d "MSSQLSvc/PVSTSAPP01.FHLBDM.com:1433" "FHLBDM\PVSTSAPP01$"
SetSPN -s "MSSQLSvc/PVSTSAPP01.FHLBDM.com:1433" "FHLBDM\FHLBDMSQLSrvc"

set /p answer=Press any key to continue...
@echo on