USE master
BACKUP DATABASE [MPF_LnCmt] TO  DISK = N'\\pfs02\SQLTempBackup\PROD\MPF_LnCmt.bak' WITH NOFORMAT, NOINIT,  NAME = N'MPF_LnCmt-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, COMPRESSION,  STATS = 10
GO
