CREATE TABLE #x -- feel free to use a permanent table
(
  drop_script NVARCHAR(MAX),
  create_script NVARCHAR(MAX)
);
  
DECLARE @drop   NVARCHAR(MAX) = N'',
        @create NVARCHAR(MAX) = N'';

-- drop is easy, just build a simple concatenated list from sys.foreign_keys:
SELECT @drop += N'
ALTER TABLE ' + QUOTENAME(cs.name) + '.' + QUOTENAME(ct.name) 
    + ' DROP CONSTRAINT ' + QUOTENAME(fk.name) + ';'
FROM sys.foreign_keys AS fk
INNER JOIN sys.tables AS ct
  ON fk.parent_object_id = ct.[object_id]
INNER JOIN sys.schemas AS cs 
  ON ct.[schema_id] = cs.[schema_id]
WHERE fk.name IN ('FK_ACTFREQCMPX2',
'FK_ACTFREQCMPX6',
'FK_ACUITY7',
'FK_DMACUITY_4',
'FK_DUTY7',
'FK_ICDSUBCATS4',
'FK_MEDRFRRLRQST_1',
'FK_MEDRFRRLRQST_21',
'FK_MEDRFRRLRQSTACTN_8',
'FK_MEDRFRRLRQSTHLTHPROB_6',
'FK_MEDRFRRLRQSTROLES_3',
'FK_MEDRFRRLRQSTROLES_7',
'FK_MENTDOCHEADERS4',
'FK_MENTDOCS7',
'FK_MENTDOCTYPEHEADERS4',
'FK_MENTDOCTYPEREVIEWS2',
'FK_MENTDOCTYPEREVIEWS7',
'FK_MENTFACTORS4',
'FK_MENTINTAKESCREENOBS4',
'FK_MENTINTAKESCREENS4',
'FK_MENTOFFINFO4',
'FK_MENTPOSTSUICIDEWATCHES6',
'FK_MENTPRVDRFAVS6',
'FK_MENTPRVDRPROFILES1',
'FK_MENTPRVDRPROFILES6',
'FK_MENTSEXUALRISKASSMNTS_14',
'FK_MENTSHUREVIEWS11',
'FK_MENTSOMPINITASSMNTCNTCTOFFS4',
'FK_MENTSOMPINITASSMNTCURNTOFFS4',
'FK_MENTSOMPINITASSMNTPRIOROFFS4',
'FK_MENTSOMPINITASSMNTSUMMS4',
'FK_MENTSOMPINTAKEOFFS4',
'FK_MENTSOMPINTAKES4',
'FK_MENTSTABLE_18',
'FK_MENTSTATIC9921',
'FK_MENTSUICIDEMHSTATUS4',
'FK_MENTSUICIDERISKASSMTS10',
'FK_MENTTEMPLATEASSOCS4',
'FK_MENTTEMPLATEASSOCS7',
'FK_MENTTEMPLATES4',
'FK_MENTTEXTSTRINGS2',
'FK_MENTTEXTSTRINGS6',
'FK_MENTTRANSFERINTAKES10',
'FK_MENTTRANSFERINTAKES2',
'FK_MENTTRANSFERSMMRY4',
'FK_MENTTRANSFERSMMRYDETAILS4',
'FK_MENTTRANSFERSMMRYSERVICES4',
'FK_MENTTXGRPFACILITATORS7',
'FK_MENTTXGRPMEMBERCMNTS4',
'FK_MENTTXGRPMEMBERS6',
'FK_MENTTXGRPS1',
'FK_MENTTXGRPS8',
'FK_MENTTXGRPSESSIONDETAILS9',
'FK_MENTTXGRPSESSIONS5',
'FK_MENTTXGRPTESTDETAILS6',
'FK_MENTTXGRPTESTS6',
'FK_MENTTXGRPTYPES4',
'FK_MESSAGEOFTHEDAY4',
'FK_NMOSACTIVE10',
'FK_ORDERSETASSOCIATIONS_1',
'FK_ORDERSETASSOCIATIONS_5',
'FK_ORDERSETCATEGORIES_5',
'FK_ORDERSETCNSLTS_7',
'FK_ORDERSETLABRQST_8',
'FK_ORDERSETLABRQSTTEST_6',
'FK_ORDERSETMEDDTLS_7',
'FK_ORDERSETMEDS_7',
'FK_ORDERSETNMOS_10',
'FK_ORDERSETOFFACTS_4',
'FK_ORDERSETPRVDRFAVS_5',
'FK_ORDERSETPTNEDTOPICS_9',
'FK_ORDERSETRADRQST_8',
'FK_ORDERSETRADRQSTVIEW_6',
'FK_ORDERSETS_4',
'FK_ORDERSETSCHEDULINGOFFACTS_6',
'FK_ORDERSETSCHEDULINGS_7',
'FK_ORDERSETSTNDORDRSIVS_6',
'FK_ORDERSETSUBCATEGORIES_5',
'FK_ORDERSNMOS16',
'FK_ORDERSNMOS4',
'FK_PLHTDM29',
'FK_RAPIDHIV4',
'FK_SECLSNRESTRAINTMONITOR_11',
'FK_TRACKINGNOTES2',
'FK_TXPLANINTERVENTIONS4',
'FK_TXPLANNOTES4',
'FK_TXPLANPGIS4',
'FK_TXPLANPGITEMPLATEDETAILS4',
'FK_TXPLANPGITEMPLATES4',
'FK_TXPLANPRVDR4',
'FK_TXPLANS4',
'FK_TXPLANS5',
'FK_TXPLANSERVICES4',
'FK_TXPLANSUMMARYS4',
'FK_PACKSLIPDSPNGS9',
'FK_PACKSLIPGRPS6',
'FK_RETURNSLIP1',
'FK_RETURNSLIP2',
'FK_RETURNSLIP8',
'FK_RETURNSLIPDSPNGS8')

INSERT #x(drop_script) SELECT @drop;

-- create is a little more complex. We need to generate the list of 
-- columns on both sides of the constraint, even though in most cases
-- there is only one column.
SELECT @create += N'
ALTER TABLE ' 
   + QUOTENAME(cs.name) + '.' + QUOTENAME(ct.name) 
   + ' ADD CONSTRAINT ' + QUOTENAME(fk.name) 
   + ' FOREIGN KEY (' + STUFF((SELECT ',' + QUOTENAME(c.name)
   -- get all the columns in the constraint table
    FROM sys.columns AS c 
    INNER JOIN sys.foreign_key_columns AS fkc 
    ON fkc.parent_column_id = c.column_id
    AND fkc.parent_object_id = c.[object_id]
    WHERE fkc.constraint_object_id = fk.[object_id]
    ORDER BY fkc.constraint_column_id 
    FOR XML PATH(N''), TYPE).value(N'.[1]', N'nvarchar(max)'), 1, 1, N'')
  + ') REFERENCES ' + QUOTENAME(rs.name) + '.' + QUOTENAME(rt.name)
  + '(' + STUFF((SELECT ',' + QUOTENAME(c.name)
   -- get all the referenced columns
    FROM sys.columns AS c 
    INNER JOIN sys.foreign_key_columns AS fkc 
    ON fkc.referenced_column_id = c.column_id
    AND fkc.referenced_object_id = c.[object_id]
    WHERE fkc.constraint_object_id = fk.[object_id]
    ORDER BY fkc.constraint_column_id 
    FOR XML PATH(N''), TYPE).value(N'.[1]', N'nvarchar(max)'), 1, 1, N'') + ');'
FROM sys.foreign_keys AS fk
INNER JOIN sys.tables AS rt -- referenced table
  ON fk.referenced_object_id = rt.[object_id]
INNER JOIN sys.schemas AS rs 
  ON rt.[schema_id] = rs.[schema_id]
INNER JOIN sys.tables AS ct -- constraint table
  ON fk.parent_object_id = ct.[object_id]
INNER JOIN sys.schemas AS cs 
  ON ct.[schema_id] = cs.[schema_id]
WHERE rt.is_ms_shipped = 0 AND ct.is_ms_shipped = 0 
AND 
fk.name IN ('FK_ACTFREQCMPX2',
'FK_ACTFREQCMPX6',
'FK_ACUITY7',
'FK_DMACUITY_4',
'FK_DUTY7',
'FK_ICDSUBCATS4',
'FK_MEDRFRRLRQST_1',
'FK_MEDRFRRLRQST_21',
'FK_MEDRFRRLRQSTACTN_8',
'FK_MEDRFRRLRQSTHLTHPROB_6',
'FK_MEDRFRRLRQSTROLES_3',
'FK_MEDRFRRLRQSTROLES_7',
'FK_MENTDOCHEADERS4',
'FK_MENTDOCS7',
'FK_MENTDOCTYPEHEADERS4',
'FK_MENTDOCTYPEREVIEWS2',
'FK_MENTDOCTYPEREVIEWS7',
'FK_MENTFACTORS4',
'FK_MENTINTAKESCREENOBS4',
'FK_MENTINTAKESCREENS4',
'FK_MENTOFFINFO4',
'FK_MENTPOSTSUICIDEWATCHES6',
'FK_MENTPRVDRFAVS6',
'FK_MENTPRVDRPROFILES1',
'FK_MENTPRVDRPROFILES6',
'FK_MENTSEXUALRISKASSMNTS_14',
'FK_MENTSHUREVIEWS11',
'FK_MENTSOMPINITASSMNTCNTCTOFFS4',
'FK_MENTSOMPINITASSMNTCURNTOFFS4',
'FK_MENTSOMPINITASSMNTPRIOROFFS4',
'FK_MENTSOMPINITASSMNTSUMMS4',
'FK_MENTSOMPINTAKEOFFS4',
'FK_MENTSOMPINTAKES4',
'FK_MENTSTABLE_18',
'FK_MENTSTATIC9921',
'FK_MENTSUICIDEMHSTATUS4',
'FK_MENTSUICIDERISKASSMTS10',
'FK_MENTTEMPLATEASSOCS4',
'FK_MENTTEMPLATEASSOCS7',
'FK_MENTTEMPLATES4',
'FK_MENTTEXTSTRINGS2',
'FK_MENTTEXTSTRINGS6',
'FK_MENTTRANSFERINTAKES10',
'FK_MENTTRANSFERINTAKES2',
'FK_MENTTRANSFERSMMRY4',
'FK_MENTTRANSFERSMMRYDETAILS4',
'FK_MENTTRANSFERSMMRYSERVICES4',
'FK_MENTTXGRPFACILITATORS7',
'FK_MENTTXGRPMEMBERCMNTS4',
'FK_MENTTXGRPMEMBERS6',
'FK_MENTTXGRPS1',
'FK_MENTTXGRPS8',
'FK_MENTTXGRPSESSIONDETAILS9',
'FK_MENTTXGRPSESSIONS5',
'FK_MENTTXGRPTESTDETAILS6',
'FK_MENTTXGRPTESTS6',
'FK_MENTTXGRPTYPES4',
'FK_MESSAGEOFTHEDAY4',
'FK_NMOSACTIVE10',
'FK_ORDERSETASSOCIATIONS_1',
'FK_ORDERSETASSOCIATIONS_5',
'FK_ORDERSETCATEGORIES_5',
'FK_ORDERSETCNSLTS_7',
'FK_ORDERSETLABRQST_8',
'FK_ORDERSETLABRQSTTEST_6',
'FK_ORDERSETMEDDTLS_7',
'FK_ORDERSETMEDS_7',
'FK_ORDERSETNMOS_10',
'FK_ORDERSETOFFACTS_4',
'FK_ORDERSETPRVDRFAVS_5',
'FK_ORDERSETPTNEDTOPICS_9',
'FK_ORDERSETRADRQST_8',
'FK_ORDERSETRADRQSTVIEW_6',
'FK_ORDERSETS_4',
'FK_ORDERSETSCHEDULINGOFFACTS_6',
'FK_ORDERSETSCHEDULINGS_7',
'FK_ORDERSETSTNDORDRSIVS_6',
'FK_ORDERSETSUBCATEGORIES_5',
'FK_ORDERSNMOS16',
'FK_ORDERSNMOS4',
'FK_PLHTDM29',
'FK_RAPIDHIV4',
'FK_SECLSNRESTRAINTMONITOR_11',
'FK_TRACKINGNOTES2',
'FK_TXPLANINTERVENTIONS4',
'FK_TXPLANNOTES4',
'FK_TXPLANPGIS4',
'FK_TXPLANPGITEMPLATEDETAILS4',
'FK_TXPLANPGITEMPLATES4',
'FK_TXPLANPRVDR4',
'FK_TXPLANS4',
'FK_TXPLANS5',
'FK_TXPLANSERVICES4',
'FK_TXPLANSUMMARYS4',
'FK_PACKSLIPDSPNGS9',
'FK_PACKSLIPGRPS6',
'FK_RETURNSLIP1',
'FK_RETURNSLIP2',
'FK_RETURNSLIP8',
'FK_RETURNSLIPDSPNGS8')
UPDATE #x SET create_script = @create;

SELECT  @drop;
Select @create;
--Select * from #x
/*
EXEC sp_executesql @drop
-- clear out data etc. here
EXEC sp_executesql @create;
*/
DROP table #x