SELECT C.NAME, 
CONVERT(NVARCHAR(MAX),CONVERT(XML,CONVERT(VARBINARY(MAX),C.CONTENT))) AS REPORTXML
FROM  REPORTSERVER.DBO.CATALOG C
WHERE  C.CONTENT IS NOT NULL
            AND  C.TYPE = 2
          AND  C.NAME LIKE 'A%'
     --AND CONVERT(NVARCHAR(MAX),CONVERT(XML,CONVERT(VARBINARY(MAX),C.CONTENT))) LIKE 'A%'
